### ISSUE TITLE
Can't create new channel

### ISSUE THREAD

**Issue by Chikrix** [GetStream/stream-chat-android#184]
When trying to create a new channel, I get a 400 bad request error with message
`{"code":4,"message":"GetOrCreateChannel failed with error: \"When using member based IDs specify at least 2 members\"","StatusCode":400,"duration":"0.00ms"}`

The way I'm creating this is 
```
val channelDetails = hashMapOf<String, Any>()
channelDetails["name"] = myChannelName
channelDetails["owner"] = "myOwnerUniqueId"
val channelType = ChannelType.DIRECT.name 
val newOrExistingChannel = streamClient.channel(channelType, channelDetails, formattedChannelIds) // list of unique member ids which might have been created or not. Always 2+
```
What could I be doing wrong here?

**Comment by tschellenbach** [comment]
That looks like a bug in the Java SDK where it's not actually sending you the members.

@tbarbugli and @adrian09h

**Comment by Chikrix** [comment]
@tschellenbach these member ids hasn't been created on Stream yet, would that be an issue?

**Comment by tschellenbach** [comment]
Yes, that's also an issue. You need to create the users before creating the
channel.

**Comment by Chikrix** [comment]
Ok. Thanks. I think that's my issue then. The message isn't very informative about that.

**Comment by tschellenbach** [comment]
I think there is something wrong with the Java SDK, our team will look into
it

**Comment by tbarbugli** [comment]
@Chikrix did you try using IDs of existing users?

**Comment by adrian09h** [comment]
Hi, @Chikrix. Thanks for your reporting.
Atm I have some questions for your creating channel.
What are `formattedChannelIds` and `ChannelType.DIRECT.name`?
**StreamChat** provides predefined types of Channel such as` livestream`, `messaging`, `gaming`, `commerce` and `team`
https://getstream.io/chat/docs/#channel_features

Please use `messaging` type.
And try below code.
```java
       val client = StreamChat.getInstance(this.application)

        val extraData = HashMap<String, Any>()
        extraData["name"] = "your-channelName"

        val members = ArrayList<String>()
        members.add("yourUserId")
        members.add("member1") /*Member(s) must be registered already to SteamChat*/
        members.add("member2") 
        //  ...
        
        extraData["members"] = members

        val channelId = "your-channelId"
        val channel = Channel(client, ModelType.channel_messaging, channelId, extraData)
        val request = ChannelQueryRequest().withMessages(10).withWatch()

        channel.query(request, object : QueryChannelCallback {
            override fun onSuccess(response: ChannelState) {

            }

            override fun onError(errMsg: String, errCode: Int) {

            }
        })
```

One more:
About  `channelDetails["owner"] = "myOwnerUniqueId"`
If you were going to use this to confirm channel owner, you don't need this field.
StreamChat exposes `created_by` field in `ChannelState` as a  `User` model.

**Comment by Chikrix** [comment]
@tbarbugli the id's are not that of existing users, so I guess that must have been the cause of my issue, I'm going to create new users and try again with their member IDs. 

@adrian09h I'm using my own custom types, I'm doing that because I'm migrating my data from Layer and used those two as my conversation types there. So I'm assuming that I need to use the same types as well for the data migration. `formattedIds` are just memberIds (formatted because I have to change my existing name format to suit Streams, removing `:` ). `ChannelType.DIRECT.name` is one of my custom channel type ("direct"). What do you think about this? I'll modify my code based on your example. Thanks

**Comment by adrian09h** [comment]
StreamChat doesn't provide the other channel type.

Please read this again

https://getstream.io/chat/docs/#channel_features

livestream: Sensible defaults in case you want to build chat like YouTube or Twitch.
messaging: Configured for apps such as Whatsapp or Messenger.
gaming: Configured for in-game chat.
commerce: Good defaults for building something like your own version of Intercom or Drift.
team: If you want to build your own version of Slack or something similar start here.

In your case, you must set channel type by `messaging`

**Comment by Chikrix** [comment]
Thanks @adrian09h. According to your docs, it says we can create our own custom channel types, so shouldn't `direct` work? Also, I want to be able to distinguish between one on one channel types and group conversations, how do I go about that if I want to use the `messaging` type? Also, there's something I don't understand about the channel types which isn't very clear, how would they differ in terms of performance and behaviour, it'll be great if there's more information on this in the docs as not everyone is familiar with those apps or the specific behaviours that separate them

**Comment by adrian09h** [comment]
@Chikrix , Sorry for my wrong comment, you can create your own type of channel.
However you need to add custom type on dashboard before creating your own type channel.

- Open your Stream dashboard
- Navigate to your app
- Menu/ Chat / Chat Overview
- Chat Types/ Add Chat Type

![image](https://user-images.githubusercontent.com/11132956/67271055-1bdbe100-f4ba-11e9-8334-b7a3e72f4706.png)

![image](https://user-images.githubusercontent.com/11132956/67271119-36ae5580-f4ba-11e9-8d6e-62d6f5277923.png)

![image](https://user-images.githubusercontent.com/11132956/67271173-50e83380-f4ba-11e9-94a9-bb2b38ba125f.png)

You can set what you want here.

**Comment by Chikrix** [comment]
Thanks @adrian09h

**Comment by Chikrix** [comment]
I'm facing an issue now creating new channels. This is the same code as I used earlier to create a channel successfully (based on the example you provided above @adrian09h . Now when I try to create a channel, I get a `NullPointerException` with mesage `Attempt to invoke virtual method 'java.util.Date com.getstream.sdk.chat.rest.Message.getDeletedAt()`. It doesn't happen only when I create a channel, but also when I try to load my channels as in the sample code. Please what could be the cause and how can I fix this?

**Comment by adrian09h** [comment]
@Chikrix , the issue was fixed by @elevenetc . Please try new version `3.0.1`.

**Comment by psylinse** [comment]
I'm receiving this issue with the latest client 3.3.0. If I create the channel like so:

```
val channel = client.channel(ModelType.channel_messaging, hashMapOf<String, Any>(), listOf(user, userToChatWith))
```

it leads to this error:

```
GetOrCreateChannel failed with error: "When using member based IDs specify at least 2 members"
```

I tried with setting the `channelId` explicitly however that leads to an unreadable channel for the second user to join:

```
val channelId = listOf(user, userToChatWith).sorted().joinToString("-")
val channel = client.channel(ModelType.channel_messaging, channelId, hashMapOf<String, Any>("members" to listOf(user, userToChatWith)))
```

which leads to this error for the second user (works fine for the user starting the channel):
`GetOrCreateChannel failed with error: "User 'chuck' with role user is not allowed to access Resource ReadChannel on channel type messaging` when I try to `.watch` the channel.

Both users are being created as a part of a log in process via a nodejs backend:

```
const client = new StreamChat(apiKey, apiSecret);

const user = Object.assign({}, data, {
  id: req.user.sender,
  role: 'user',
  image: `https://robohash.org/${req.user.sender}`,
});
const token = client.createToken(user.id);
await client.updateUsers([user]);
```

What am I doing wrong?

**Comment by psylinse** [comment]
Okay, on further investigation I _think_ I may have found a bug in the library. If I do initalize the channel with a 

```
.watch(ChannelWatchRequest(), object : QueryWatchCallback {` 
```

it seems to fail to pass the member information in the body of the request, causing the above error. Changing this to:

```
channel.query(ChannelQueryRequest().withMessages(25).withWatch(), object : QueryChannelCallback {
```

seems to work great. Is there some semantics around `.watch` I'm missing or is this a bug?

@elevenetc @adrian09h

**Comment by elevenetc** [comment]
@psylinse thanks for reporting the problem. I created separate issue for your problem: https://github.com/GetStream/stream-chat-android/issues/422

**Comment by nh2d** [comment]
This is absolutely not fixed @elevenetc . And still hitting this issue on python client. And the docs do not even match up... this code is a disaster...


https://getstream.io/chat/docs/python/creating_channels/?language=python

```
channel = Channel("messaging", None, custom_data=dict(members=["thierry"]))
# Note: query method creates a channel
channel.query()

```

this doesn't work. the signature isn't even consistent with what the python SDK expects...



```
channel = Channel("messaging", "general")
channel.create("<user-id>")

```

this is also inconsistent with what library expects. I'm calling this from my backend python server and i'm getting 👍 

`stream_chat.base.exceptions.StreamAPIException: StreamChat error code 4: GetOrCreateChannel failed with error: "When using member based IDs specify at least 2 members""`



what is going on here? almost nothing i've tried in docs is working. is this project still being maintained at all?

**Comment by nh2d** [comment]
Many years later this is still very much an issue.

**Comment by brianMxBm** [comment]
Facing this issue with the JS SDK. @nh2d Did you perhaps figure out what was wrong?
